name: build and deploy
on:
  push:
    branches: 
      - main
  workflow_dispatch:

env:
  HUGO_BASEURL: https://toy757.github.io/hugo-example/

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v3
        with:
          # サブモジュールも取得
          submodules: recursive
          fetch-depth: 0
      - name: hugoドキュメントのビルド
        # 参考：https://github.com/klakegg/actions-hugo/blob/master/action.yml
        # 別のActionもある模様
        # 参考：https://github.com/peaceiris/actions-hugo
        uses: klakegg/actions-hugo@1.0.0
        with:
          target: public
          source: .
          # docsyテーマの依存関係にはSASS, SCSSが含まれる
          # SASS,SCSSをcssに変換するにはhugo extended versionが必要
          # 参考：https://gohugo.io/troubleshooting/faq/#i-get--this-feature-is-not-available-in-your-current-hugo-version
          image: ext-ubuntu
          # Dev Conatinerで利用するHugoバージョンに合わせる
          version: 0.101.0
          # 公開ページのみをビルド
          env: production
          # baseURLを変更
          # GitHub Pageでは公開URLが、https://<ユーザ名>.github.io/<リポジトリ名>/となるため
          command: -b ${{ env.HUGO_BASEURL}}
      - name: GitHub Pagesに公開
        # GitHub Pagesへの公開は、ブランチ方式とGitHub Actions(Beta)がある
        # ここではブランチ方式を採用する
        # ブランチ方式では、特定のブランチにあるリソースをそのまま静的コンテンツとして公開する
        # Pagesの有効化にはリポジトリ設定からPagesの有効化が必要
        # 参考：https://docs.github.com/ja/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site
        uses: peaceiris/actions-gh-pages@v3
        # mainブランチ時のみ実施
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # ./publicは以下のドキュメントを公開
          publish_dir: ./public
